name: Android Build

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


          # Node 环境
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm


      # 安装依赖
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Install build dependencies
        run: npm install @vercel/nft --save-dev


      # 构建前端
      - name: Build Web App
        run: |
          chmod +x scripts/*.sh
          printf "front\nclient\n" | npm run build


      # 同步 Capacitor Android
      - name: Capacitor sync
        run: npx cap sync android

      # Java环境
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle


      # 编译APK
      - name: Build APK
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug


      # 上传APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: android/app/build/outputs/apk/debug/*.apk
